import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Locale, defaultLocale } from "@/i18n/settings";
import { getLanguageFromPath, initTranslations } from "@/i18n/server";
import { TranslationsProvider } from "@/i18n/TranslationsProvider";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang?: string };
}>) {
  // Initialize translations on the server
  const lang = params.lang as Locale || defaultLocale;
  const { locale, resources } = await initTranslations(lang);
  
  // Only pass serializable data to client components
  const serializedResources = JSON.parse(JSON.stringify(resources));

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950 text-gray-900 dark:text-gray-100`}
      >
        <TranslationsProvider
          locale={locale}
          resources={serializedResources}
        >
          <div className="min-h-screen flex flex-col">
            <header className="sticky top-0 backdrop-blur-md bg-white/70 dark:bg-gray-900/70 border-b border-gray-200 dark:border-gray-800 shadow-sm z-10">
              <div className="flex justify-between items-center max-w-6xl mx-auto p-4">
                <div className="flex items-center space-x-2">
                  <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold">M</div>
                  <h1 className="text-xl font-bold bg-gradient-to-r from-blue-600 to-indigo-600 inline-block text-transparent bg-clip-text">NextLingo</h1>
                </div>
                <LanguageSwitcher />
              </div>
            </header>
            <main className="flex-grow py-8 px-4">
              <div className="max-w-6xl mx-auto">
                {children}
              </div>
            </main>
            <footer className="border-t border-gray-200 dark:border-gray-800 py-6 px-4 bg-white/50 dark:bg-gray-900/50 backdrop-blur-md">
              <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
                <div className="flex items-center space-x-2">
                  <div className="w-6 h-6 rounded-full bg-gradient-to-tr from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold text-xs">M</div>
                  <span className="text-sm font-medium">NextLingo © {new Date().getFullYear()}</span>
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  {locale === 'en' && 'A beautiful multilingual Next.js application'}
                  {locale === 'es' && 'Una hermosa aplicación Next.js multilingüe'}
                  {locale === 'pt' && 'Uma bela aplicação Next.js multilíngue'}
                </div>
              </div>
            </footer>
          </div>
        </TranslationsProvider>
      </body>
    </html>
  );
}
